# Generated by Django 5.1.1 on 2024-10-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzatracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='image',
            field=models.URLField(max_length=250),
        ),
    ]
