# Generated by Django 5.1.1 on 2024-10-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzatracker', '0002_alter_pizza_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='desc',
            field=models.TextField(default=2, max_length=250),
            preserve_default=False,
        ),
    ]
