# Generated by Django 5.1.1 on 2024-10-07 03:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzatracker', '0003_pizza_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='amout',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
